name: 'github-beekeeper-chat'
description: 'Sends a message to Beekeeper ChatsV2'
author: 'Beekeeper AG'
inputs:
  tenant:
    required: true
    description: "FQDN of the tenant to send a message to"
  chat:
    required: true
    description: "ID of the chat to send a message to"
  apikey:
    required: true
    description: "API key to use to send a message to the chat"
  message:
    required: true
    description: "Message to send"
runs:
  using: 'node16'
  main: 'dist/index.js'
